/**
 * Shared component styles re-authored from the Tailwind @apply classes that
 * used to live in src/index.css. Components import via
 * `import { shared } from '../../styles/shared'`.
 * Generated by scripts/gen-shared-stylex.mjs.
 */
import * as stylex from '@stylexjs/stylex';
import { colors } from './tokens.stylex';

export const shared = stylex.create({
  card: {
    "backgroundColor": colors["--sos-bg-white-slate-850"],
    "borderWidth": 1,
    "borderStyle": "solid",
    "borderColor": colors["--sos-border-slate-200-slate-700_50"],
    "borderRadius": "0.75rem",
    "boxShadow": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
  },
  input: {
    "backgroundColor": colors["--sos-bg-white-slate-900"],
    "borderWidth": 1,
    "borderStyle": "solid",
    "borderColor": colors["--sos-border-slate-300-slate-700"],
    "borderRadius": "0.5rem",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "fontSize": "0.875rem",
    "lineHeight": "1.25rem",
    "color": colors["--sos-text-slate-900-slate-100"],
    "minHeight": "2.75rem",
    "::placeholder": {
      "color": colors["--sos-text-slate-400-slate-500"],
    },
    ":focus": {
      "borderColor": "#6366f1",
      "boxShadow": "0 0 0 0px #fff, 0 0 0 2px #6366f180",
    },
  },
  btn: {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "borderRadius": "0.5rem",
    "paddingLeft": "1rem",
    "paddingRight": "1rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "fontSize": "0.875rem",
    "lineHeight": "1.25rem",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, text-decoration-color, fill, stroke",
    "minHeight": "2.75rem",
  },
  btnPrimary: {
    "backgroundColor": "#4f46e5",
    "color": "#ffffff",
    ":hover": {
      "backgroundColor": "#6366f1",
    },
  },
  btnSecondary: {
    "backgroundColor": colors["--sos-bg-slate-200-slate-700"],
    "color": colors["--sos-text-slate-800-slate-100"],
    ":hover": {
      "backgroundColor": colors["--sos-bg-slate-300-slate-600"],
    },
  },
  btnGhost: {
    "color": colors["--sos-text-slate-600-slate-300"],
    ":hover": {
      "backgroundColor": colors["--sos-bg-slate-200-slate-800"],
      "color": colors["--sos-text-slate-900-white"],
    },
  },
});
