name: PR title check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  validate-title:
    name: Validate PR title
    if: ${{ github.event.pull_request.base.ref != 'testnet' && github.event.pull_request.base.ref != 'production' }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            chore
            refactor
            test
            ci
            build
            perf
            revert
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            should not start with an uppercase character.
          validateSingleCommit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
